language: node_js
node_js:
- stable
before_script:
- npm run build
deploy:
  skip_cleanup: true
  provider: npm
  email: venterschalk@gmail.com
  api_key:
    secure: gIIVaqboFYx70hrdI/16/MC1vxaP1Afl2i2FP62dlbRxwiwPtdVLQsk+//aycafCRiVUsLQiaOvwa213xVVSWPniIhNMyf6vqc2N/+xb5XLeKKTivfDWb3OYYbDn2dYawcYCD7zHqOEEzOWWuMOuYKuaj6siGcSEzbBcuLEK+GIB07Z9onb8ZgqnJGsZHlDARgtzhMmK9zT78KoLfsJdHvZjSuAI7C39qsYJjxurib4oJ4lLRjz4NUMGqsgB2iK2RFkPMA2vEaiAR0UZO14clyq+HXVqR2uXtSpNi0g/SeQCjge6rc51vu7KqvNEpY5d+Vqvp7XUceaVFDJHl9wV7yMwvonKEhKxadXeDq99poNcd9rzlq9/TE1WVYV0y9dO5CESkqsgLKg7m26Sl+j9OpIhL6pWLFdmrGuZ5AY+C+P7GO39yY+V25Xym866VJhAMMzD/dDxAlUNV0LkRr0AzCj9q06WattebYa4yzA8MSp/z+3190b9UuVyM6e515RqaIDxX6iUoRfVihQRSOtZ2qLnb7JqNExm4cfIcin4tq+Bo4nrcTDEIcvhm7BXqG5M2Wnw8wSJdB3kpqVh3os7KQ3alvjwIjNIjtvzocQjOocDM5X+5Qrgroz+VjvkOQDk4tCxF0o9O8sNOmw0uP2z4dYdSBCUlH19VVuOg913kjc=
  on:
    branch: master
