language: node_js
node_js:
- stable
before_script:
- npm run build
deploy:
  skip_cleanup: true
  provider: npm
  email: venterschalk@gmail.com
  api_key:
    secure: QwGOS5asqrGvVWYBlfCeIF8zoNHTLz2+h1CiPlW70udMbU4zMBfWAiNq+o5bVRAFtJRGv44MrcJvfrJtdSepoKPVQ8DbHEa4sqAodLig7eJGPQ3Tpuhb26pGDqYh9TJAm71ITyybJKVQ4yJpd/IcE7Muh/CCB7zatpPpOepnabZJCegvgN0QkCkKL5jgtQIrOA0fNxisq35hj7fDMHhX3QsLaUY4YPx/P6jlw8k7jIhxEhLTlW2nHXX+Gvhafh4T6iVruaz/rCTOIBhE4b1a+8Rn1pwTiHwKTKjL1YXO7EofoAGpiXz/tle+MMJeMqCN4WqhTGSWmpumBSIo0YnPAfdDjTB1OoX2yGjpDea39LvPY29R9+VoD0v+lUUtyRlm51oDcOt/rEV78MTxBFP4VDb1VYmZkCjlwK0jsPNOpxKiUXcfT1QagN+cauIDjVeyf2yvyf7Z/C1PKnujeVikfbekTzIQa+7yxGgp+jfHNQSBG8iFjaoEfJD+Rj01wMmXpRdcDBKlkzwuTpbN4u9urdMC2E6mEIPuZK7BV6gKxmn3SCp/M+LkNHtD/sVcys1qUiXysMWVARxu21OroEd/blyP7W6uX0OPThPPMb8hZ2jnzAT+8u8X7xugABxlt/dWOvKy4Ogfnobp6fZ2k5lUh4T9emudl40HVq4yDOS8tfY=
  on:
    branch: master
