language: node_js
node_js:
- stable
before_script:
- npm run build
deploy:
  skip_cleanup: true
  provider: npm
  email: venterschalk@gmail.com
  api_key:
    secure: BU66unAC4FXKXP5W/Ua6eeIdp5fRnpOj2ib53d45UVsQco6FCvCP1jBs7+OMRyPeYVtH5rYIpZ5/n/QpbWo7NkmZyQcrLY7piYt2L5/GT7dVrgsZvZmAkZkYvv2PTPmCSUaYUsDbUBak/9CWmItm6iHz6+T4ls6OcZApGEiR4d6v4yPZ/x1yn4kx3MhZXK6PeOZFB4rLI9k0u6hNq8tdrMp5bhkFlxv8WG9oj1jW3zVknpBNgJmueA8lv1C+Ucx+zPkZRKJ8lFF74DVGCE+1jig4QJOUoF+hhhuG97/3FOI1yXJIljES01isDNcTvENLuOEW1w2SQa10MWo+5f4gosz77JkR8IcNDMhq1+5WAGLI/040MjU4H1NzxV9Zb3pDtqxjzoKYjQmcum8aKAcRbvIDiuHGQhHQ/fCGZbxc+L3owQzU/nLJbuv23BWZVaCsrbSaHHNg+GXqUHcqr0Ogw1ov8dKWirwGZ3fzE8mxtRB9iMrQtHvTfjD7N1I6hyS45/wo3tbJ8uMAeuRes5Oge2K92k5nbt4R72/eQ4Iglby4GC/woCmSUUpMhnXhPkZzbMvO+ycCaJyMJ5mCWjwG16QvKYxgKJsCZ4vHHYRfTpVr1F2Rsbh/KmiXiZmI5N+6eP/cOpNtPqK+0CdDy9aK82r+H4gVON9VIXUSBLTPzho=
  on:
    branch: master
