language: node_js
node_js:
- stable
before_script:
- npm run build
deploy:
  skip_cleanup: true
  provider: npm
  email: venterschalk@gmail.com
  api_key:
    secure: oiynnsNeMIoDLG7+jOuYK6lW4vfWn+r25swLuqhMuwc5FeuwX3//m0t4pwr5/YG0QMr0aJOPg9i3JiXzJ+e/KW2XXfLmc0zzIJhxd/uNiyZHUtMK3VdVTcJLUkr7uQaTHg+mt02IqU6mFVPliBQCyh1+PKdPJcOc0jrR3Mfpentcdeyk+vZPI/jDKAXsaVORalTiho4Vl0rouKZhchctAowLYON6f0E4OKeP1HY6fYsUV/awlG7ng7D4KXR710i/qZGmWM3b47pXl5J4PuS5pUThrQ2HvKSqcz0p+y7G0BW3Ku00EktG+ws/aCkGn5oyK/G30bahOtIkh65nBTJMuNJNSDuuZB2wkiZzW2KIUra/Uaj7yo59CEPcIgiae17CAKZ4b5sBdv4kcZzT13R1Q2yZm3jEEP/y61Hs7BpiTlH+04MDzt/JbUWlYP2CMCkunmsz8+FoD8hnsFedYKaVH7lb62o0ET5L6qcSxFMEl96IFvgQ7Adf2LOQUplfm5Gl1+c9cBWSkwJssLQE1tV8uo4+iszilck9qwsBf66UGjLgbsWB6bspiL5MDKa/64/ldVjxBohJc8oVPyH9aLM3lOsxAnCq6ixDBks8E8WJ+YitWG0jH6E9rjjGSH7md+xDk8VG1GRzpjAcVYbjvLi7PNFGMNf1zu/TYe6PItXHKsg=
  on:
    branch: master
